<?php

/**
 * @file
 * Contains malp_views_bootstrap.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\views_bootstrap\ViewsBootstrap;
use Drupal\Core\Template\Attribute;

/**
 * Implements hook_help().
 */
function malp_views_bootstrap_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the malp_views_bootstrap module.
    case 'help.page.malp_views_bootstrap':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Override some bootstrap views') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function malp_views_bootstrap_theme() {
  return [
    'malp_views_bootstrap' => [
      'render element' => ['children'],
    ],
  ];
}

/**
 * Implements hook_preprocess_views_bootstrap_accordion().
 */
function malp_views_bootstrap_preprocess_views_bootstrap_accordion(array &$vars) {
  // $view = $vars['view'];
  // foreach ($vars['rows'] as $id => $row) {
  //   $vars['rows'][$id]['title'] = [
  //     $view->style_plugin->getField($id, 'title'),
  //     ];
  // }
}
